apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: resources
spec:
  version: "v0.1.0"
  platforms:
    - selector:
        matchLabels:
          os: darwin
        arch: amd64
      uri: https://github.com/howardjohn/kubectl-resources/releases/download/v0.1.0/kubectl-resources_0.1.0_Darwin_x86_64.tar.gz
      sha256: f27cc3474df627d0d9b55eee6514a9d7c7858d1a878af75c07ad15b3a5272d75
      bin: kubectl-resources
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/howardjohn/kubectl-resources/releases/download/v0.1.0/kubectl-resources_0.1.0_Linux_x86_64.tar.gz
      sha256: ad3d1a126b106a38fb92ae76bb728b00ed8b4ef02eef574456b73f21c28affb3
      bin: kubectl-resources
  shortDescription: >-
    Access Kubernetes resource requests, limits, and usage.
  homepage: https://github.com/howardjohn/kubectl-resources
  description: |
    Access Kubernetes resource requests, limits, and usage.
