pull_request_rules:
  - name: automatic merge
    conditions:
      - "status-success=buildkite/build"
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "label!=do not merge"
    actions:
      merge:
        method: squash
      delete_head_branch: {}
  - name: automatic merge for admin
    conditions:
      - "status-success=buildkite/build"
      - "author=howardjohn"
      - "label!=do not merge"
    actions:
      merge:
        method: squash
        strict: false
      delete_head_branch: {}
